eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/malaxiangjiaopipixia/shop.git
          username: malaxiangjiaopipixia
          password: 123456x@@@
management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

